### ISSUE TITLE
Creating schema failure

### ISSUE THREAD

**Issue by gmauro** [ht-diva/gwasstudio#11]
https://github.com/ht-diva/gwasstudio/blob/3e3bc82e9ab54240d41d2b7498694568eef543a0/gwasstudio/cli/ingest.py#L60

It fails to create the schema:

```
Traceback (most recent call last):
  File "/home/gianmauro.cuccuru/miniforge3/envs/gwasstudio/bin/gwasstudio", line 8, in <module>
    sys.exit(main())
  File "/home/gianmauro.cuccuru/miniforge3/envs/gwasstudio/lib/python3.10/site-packages/gwasstudio/main.py", line 113, in main
    cli_init(obj={})
  File "/home/gianmauro.cuccuru/miniforge3/envs/gwasstudio/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/gianmauro.cuccuru/miniforge3/envs/gwasstudio/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/gianmauro.cuccuru/miniforge3/envs/gwasstudio/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gianmauro.cuccuru/miniforge3/envs/gwasstudio/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gianmauro.cuccuru/miniforge3/envs/gwasstudio/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/gianmauro.cuccuru/miniforge3/envs/gwasstudio/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/gianmauro.cuccuru/miniforge3/envs/gwasstudio/lib/python3.10/site-packages/gwasstudio/cli/ingest.py", line 47, in ingest
    ingest_to_s3(ctx, input_file_list, uri)
  File "/home/gianmauro.cuccuru/miniforge3/envs/gwasstudio/lib/python3.10/site-packages/gwasstudio/cli/ingest.py", line 60, in ingest_to_s3
    create_tiledb_schema(uri, cfg)
  File "/home/gianmauro.cuccuru/miniforge3/envs/gwasstudio/lib/python3.10/site-packages/gwasstudio/utils/__init__.py", line 169, in create_tiledb_schema
    tiledb.Array.create(uri, schema, ctx=ctx)
  File "libtiledb.pyx", line 683, in tiledb.libtiledb.Array.create
  File "libtiledb.pyx", line 353, in tiledb.libtiledb._raise_ctx_err
  File "libtiledb.pyx", line 338, in tiledb.libtiledb._raise_tiledb_error
tiledb.cc.TileDBError: S3: Error while listing with prefix 's3://tiledb/public_data/__schema/' and delimiter '/'[Error Type: 23] [HTTP Response Code: 403] [Excep
tion: InvalidAccessKeyId] [Remote IP: *.*.*.*] [Request ID: 564964660] [Headers: 'connection' = 'keep-alive' 'content-length' = '202' 'date' = 'Sat, 30 Nov 20
24 10:26:18 GMT' 'x-amz-request-id' = '564964660'] : The access key ID you provided does not exist.
```

**Comment by gmauro** [comment]
Seems to ignore the configuration exposed by the context
@bruno-ariano Do you have any suggestion on this?

**Comment by gmauro** [comment]
the access key must be enclosed in quotes.
